### ISSUE TITLE
Can you teach me how to create input data?

### ISSUE THREAD

**Issue by linan2** [auspicious3000/WaveNet-Enhancement#4]
Hi,
If you can upload or send me a part your .mat data? I want to  look at your data structrue.
Thank  you very much!
My e-mail is linanvae@163.com   
Thank you.

**Comment by linan2** [comment]
If the input data must int?

**Comment by auspicious3000** [comment]
They have been uploaded to assets.

**Comment by linan2** [comment]
Thank you very much, Sir.
