### ISSUE TITLE
Which pretrained model to liklihood training

### ISSUE THREAD

**Issue by shifaspv** [auspicious3000/WaveNet-Enhancement#6]
Hi,
  I got a set of files on my Logging directory after the prior trained. which one should be the input to likelihood? 
there are files 'checkpoint' & 'bawn_pr_v2.ckpt-349816' and 'losses'

**Comment by auspicious3000** [comment]
This questions is more of tensorflow questions. Just load the model in the standard way in tensorflow.

**Comment by shifaspv** [comment]
Thanks for the commends, apology for asked this question, below link might be useful for some one to fix this issue in future.

https://github.com/tensorflow/tensorflow/issues/7696
