### ISSUE TITLE
Command to use trained model to test on noisy speech

### ISSUE THREAD

**Issue by shifaspv** [auspicious3000/WaveNet-Enhancement#7]
Hi,
 You have not mentioned about how do we use the trained model for testing on a noisy speech. Could you please tell me that? Do I need to write separate script myself for this?

**Comment by auspicious3000** [comment]
I didn't upload the testing code because it was very slow. You can follow the procedures described in the paper for testing. 
I may upload the testing code later once it has been accelerated.

**Comment by shifaspv** [comment]
Thanks for the responses.
If you don't mind, could you sent that (the old version) to me personally to my mail: shifaspv001@gmail.com. 
Since I am new in Tensorflow,  for me it may take days to implement.
