### ISSUE TITLE
Should I expect this model generalize well on unseen speaker?

### ISSUE THREAD

**Issue by JiachuanDENG** [auspicious3000/WaveNet-Enhancement#8]
It is said this model is  "speaker dependent", but can anyone give me an intuitive view why this model should be "speaker dependent"? Now that the model has a good generalization on different noises, why it can not generalize well on different speakers? Or should I expect this model generalize well if I add more speaker sources?

**Comment by auspicious3000** [comment]
The prior model is speaker dependent. If you add more speakers, the generated speech will switch between different voices.
